"""Corrige nome da tabela Veiculo

Revision ID: 43b75678fef8
Revises: 5fa9de446c35
Create Date: 2025-08-06 16:14:49.224196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b75678fef8'
down_revision = '5fa9de446c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('veiculo')
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.String(length=255), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('observacao')

    op.create_table('veiculo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('numero_frota', sa.INTEGER(), nullable=False),
    sa.Column('tipo_frota', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('observacao', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
