"""criação inicial

Revision ID: e81823d2818b
Revises: 
Create Date: 2025-08-01 19:02:32.986505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81823d2818b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_frota', sa.Integer(), nullable=False),
    sa.Column('tipo_frota', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_frota')
    )
    op.create_table('programacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('compareceu', sa.Boolean(), nullable=True),
    sa.Column('remarcado_para', sa.Date(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('motivo_classificado', sa.String(length=50), nullable=True),
    sa.Column('habilitado_para_vistoria', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programacoes')
    op.drop_table('veiculos')
    # ### end Alembic commands ###
